### PR TITLE
Add support for Urdu

### PR DESCRIPTION
**Pull request by anuragshas**

### CODE REVIEW

**Comment by goru001** [comment]
@anuragshas Thanks for the great work!
Actually I'm under the pump to complete a few things this week in office (and I'm late), so will only be able to test+approve your MR by the end of this week. Sorry about that! 
I will get back to you by Saturday for sure. Thanks!

**Comment by goru001** [comment]
@anuragshas For the "predict_next_words" function, what the LM predicts we append it at the end of text. Do you think that should be appended at the beginning of text for Urdu? Just wanted to know while training LM did you take care of the fact that Urdu is read from right to left?

**Comment by goru001** [comment]
@anuragshas I've reverted this PR for now, let's merge it again after your reply.

**Comment by anuragshas** [comment]
It's not required if we are reading files in utf-8, I am showing an example from google translate, for input sentence and their results
Input Sentence
Result

**Comment by anuragshas** [comment]
If you type urdu in console it will be from left to right but in case of editors they have adjustments made for RTL language

**Comment by anuragshas** [comment]
Here is a result for predicting next 150 words
Screenshot from 2019-05-25 17-40-53

**Comment by anuragshas** [comment]
Only problem I can see is that it is also generating latin characters because wikipedia had english in it. I had missed that case

**Comment by goru001** [comment]
> If you type urdu in console it will be from left to right but in case of editors they have adjustments made for RTL language

@anuragshas Yes right. Do you think we should have something like the following in predict_next_words function:

`if language_code=='ur':
        text = prediction + input    
`
From what I see from my tests, it seems utf-8 encoding is taking care of the fact that when two RTL strings are being added, they are added in right to left fashion, and not in left to right. 
So, [for this line](https://github.com/goru001/inltk/blob/master/inltk/inltk.py#L42), behavior of `+` changes automatically if its RTL language or LTR language. So I assume this will work as long as encoding is utf-8 (which is default for python3 strings) **and** this is independent of whether you run iNLTK in console or in an editor! 

> It's not required if we are reading files in utf-8

Did you mean what I said above when you said this? If yes, can you add a comment above this line specifying that utf-8 encoding takes care of RTL and LTR languages, and we'll be good to go.

**Comment by anuragshas** [comment]
> If you type urdu in console it will be from left to right but in case of editors they have adjustments made for RTL language

What I meant to convey that underneath all languages are handled in LTR fashion and for display purposes they are changed in editors and browsers
>So I assume this will work as long as encoding is utf-8 (which is default for python3 strings) and this is independent of whether you run iNLTK in console or in an editor!

Yes you got it right until and unless we are handling strings in utf-8 format we don't need to care about LTR or RTL languages. Yes I will add the comment

**Comment by goru001** [comment]
great, thanks! Let me know when you've the PR.

**Comment by anuragshas** [comment]
I have created the new PR

**Comment by goru001** [comment]
Yup, thanks. It has been merged and released in v0.5 . Thank you for your contributions!

**Pull request merged**
